--HAVAING | HAVING CLAUSE IS USED WITH GROUP BY TO RESTRICT THE GROUP OF RETURNED ROWS.
DROP TABLE PERSON CASCADE CONSTRAINTS PURGE;
CREATE TABLE PERSON(NAME VARCHAR2(90), AGE NUMBER, SALARY NUMBER, STATE VARCHAR2(90));
INSERT INTO PERSON VALUES('DFS', 43, 10000, 'BIHAR');
INSERT INTO PERSON VALUES('DFS', 43, 20000, 'BIHAR');
INSERT INTO PERSON VALUES('DFS', 43, 30000, 'BIHAR');
INSERT INTO PERSON VALUES('DFS', 43, 10000, 'BIHAR');
INSERT INTO PERSON VALUES('DFS', 43, 50000, 'BIHAR');
INSERT INTO PERSON VALUES('DFS', 43, 60000, 'BIHAR');
INSERT INTO PERSON VALUES('DFS', 43, 70000, 'BIHAR');
INSERT INTO PERSON VALUES('DFS', 43, 9000, 'BIHAR');
INSERT INTO PERSON VALUES('DFS', 43, 9000, 'GOA');
INSERT INTO PERSON VALUES('DFS', 43, 10000, 'GOA');
INSERT INTO PERSON VALUES('DFS', 43, 10000, 'GOA');
INSERT INTO PERSON VALUES('DFS', 43, 20000, 'GOA');
INSERT INTO PERSON VALUES('DFS', 43, 30000, 'GOA');
INSERT INTO PERSON VALUES('DFS', 43, 30000, 'GOA');
INSERT INTO PERSON VALUES('DFS', 43, 40000, 'TAMIL');
INSERT INTO PERSON VALUES('DFS', 43, 60000, 'TAMIL');
INSERT INTO PERSON VALUES('DFS', 43, 10000, 'TAMIL');
INSERT INTO PERSON VALUES('DFS', 43, 4000, 'TAMIL');
INSERT INTO PERSON VALUES('DFS', 43, 50000, 'TAMIL');
INSERT INTO PERSON VALUES('DFS', 43, 10000, 'UP');
INSERT INTO PERSON VALUES('DFS', 43, 10000, 'UP');
INSERT INTO PERSON VALUES('DFS', 43, 1000, 'UP');
INSERT INTO PERSON VALUES('DFS', 43, 70000, 'UP');
INSERT INTO PERSON VALUES('DFS', 43, 60000, 'UP');
INSERT INTO PERSON VALUES('DFS', 43, 90000, 'UP');

SELECT STATE,COUNT(*),MIN(SALARY) FROM PERSON WHERE SALARY <= 10000 GROUP BY STATE HAVING COUNT(*) >= 2;--HAVING IS PERFORMED ON THE AGGREGATE FUNCTION OF THE GROUP BY COLUMN
SELECT STATE,COUNT(*),MAX(SALARY) FROM PERSON WHERE SALARY <= 10000 GROUP BY STATE HAVING COUNT(*) >= 2;--HAVING IS PERFORMED ON THE AGGREGATE FUNCTION OF THE GROUP BY COLUMN
SELECT STATE,COUNT(*),MAX(SALARY) FROM PERSON GROUP BY STATE;--HAVING IS PERFORMED ON THE AGGREGATE FUNCTION OF THE GROUP BY COLUMN
SELECT STATE,COUNT(*) TOTAL,MAX(SALARY) HIGHEST, MIN(SALARY) LOWEST FROM PERSON GROUP BY STATE;