
--Displaying record across pages is called pagination
DROP TABLE PERSON;
DROP SEQUENCE PERSON_ID;
CREATE TABLE PERSON(ID NUMBER, NAME VARCHAR2(90), AGE NUMBER(2));
CREATE SEQUENCE PERSON_ID START WITH 1 INCREMENT BY 1;
INSERT INTO PERSON VALUES(PERSON_ID.NEXTVAL, 'DEV', 24);
INSERT INTO PERSON VALUES(PERSON_ID.NEXTVAL, 'DEV', 24);
INSERT INTO PERSON VALUES(PERSON_ID.NEXTVAL, 'DEV', 24);
SELECT * FROM PERSON;

--SINCE ROWNUM IS NOT A COLUMN, WE NEED MAKE SUBQUERRY TO CREATE ROWNUM COLUMN
SELECT NAME,AGE FROM (SELECT NAME,AGE,ROWNUM RN FROM PERSON) WHERE RN BETWEEN 1 AND 5;