--UPDATE VIEW 
--CREATE OR REPLACE IS USED TO MODIFY VIEW WITHOUT DELETING IT.
CREATE TABLE PRODUCT(PRODUCT_INDEX, NAME VARCHAR2(90));
CREATE SEQUENCE PRODUCT_SEQ START WITH 1 INCREMENT BY 1;
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL, 'ABC');
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL, 'EFG');
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL,'VIJAY');
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL,'SWETHA');
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL,'RUPA');
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL,'SHIVAM');
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL,'MAHESH');

CREATE VIEW PRO_1 AS SELECT * FROM PRODUCT WHERE ID>=4;
SELECT * FROM PRO_1;
CREATE OR REPLACE VIEW PRO_1 AS SELECT * FROM PRODUCT WHERE ID>=3;

DROP VIEW PRO_1;